/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MatchRouteImport } from './routes/match'
import { Route as ExtractRouteImport } from './routes/extract'
import { Route as ExportRouteImport } from './routes/export'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTidalRouteImport } from './routes/auth/tidal'
import { Route as AuthSpotifyRouteImport } from './routes/auth/spotify'

const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractRoute = ExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTidalRoute = AuthTidalRouteImport.update({
  id: '/auth/tidal',
  path: '/auth/tidal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSpotifyRoute = AuthSpotifyRouteImport.update({
  id: '/auth/spotify',
  path: '/auth/spotify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/extract': typeof ExtractRoute
  '/match': typeof MatchRoute
  '/auth/spotify': typeof AuthSpotifyRoute
  '/auth/tidal': typeof AuthTidalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/extract': typeof ExtractRoute
  '/match': typeof MatchRoute
  '/auth/spotify': typeof AuthSpotifyRoute
  '/auth/tidal': typeof AuthTidalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/extract': typeof ExtractRoute
  '/match': typeof MatchRoute
  '/auth/spotify': typeof AuthSpotifyRoute
  '/auth/tidal': typeof AuthTidalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/export'
    | '/extract'
    | '/match'
    | '/auth/spotify'
    | '/auth/tidal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/export' | '/extract' | '/match' | '/auth/spotify' | '/auth/tidal'
  id:
    | '__root__'
    | '/'
    | '/export'
    | '/extract'
    | '/match'
    | '/auth/spotify'
    | '/auth/tidal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportRoute: typeof ExportRoute
  ExtractRoute: typeof ExtractRoute
  MatchRoute: typeof MatchRoute
  AuthSpotifyRoute: typeof AuthSpotifyRoute
  AuthTidalRoute: typeof AuthTidalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract': {
      id: '/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof ExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/tidal': {
      id: '/auth/tidal'
      path: '/auth/tidal'
      fullPath: '/auth/tidal'
      preLoaderRoute: typeof AuthTidalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/spotify': {
      id: '/auth/spotify'
      path: '/auth/spotify'
      fullPath: '/auth/spotify'
      preLoaderRoute: typeof AuthSpotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportRoute: ExportRoute,
  ExtractRoute: ExtractRoute,
  MatchRoute: MatchRoute,
  AuthSpotifyRoute: AuthSpotifyRoute,
  AuthTidalRoute: AuthTidalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
